<a href="https://colab.research.google.com/github/anapowarchuk/processamento-de-imagens/blob/main/Aula_1_Introdu%C3%A7%C3%A3o_ao_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Material elaborado por Ana Xavier, durante as aulas de Processamento Digitais de Imagens, ministradas pela Professora Dra. Carla Diniz L. Becker, para o curso de Informática Biomédica da Universidade Federal de Ciências da Saúde de Porto Alegre.

# **Aula 1 - Introdução ao Numpy**
### 04/11/2021 [Aula Assincrona]

Importando a biblioteca Numpy

In [ ]:
import numpy as np

## **A estrutura de uma matriz NumPy: uma visão sobre memória**

Gera os inteiros de zero a oito e coloca-os em uma matriz 3x3

In [ ]:
x = np.arange(9).reshape((3, 3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
x.strides

(24, 8)

In [ ]:
y = x[::2, ::2]
y


array([[0, 2],
       [6, 8]])

In [ ]:
y.strides

(48, 16)

In [ ]:
y[0, 0] = 100
x

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8]])

Transpondo o array, usando "T"

In [ ]:
 xT = x.T
 xT

array([[100,   3,   6],
       [  1,   4,   7],
       [  2,   5,   8]])

In [ ]:
xT.strides

(8, 24)

Mudando a forma do array

In [ ]:
z = x.reshape((1, 9))
z

array([[100,   1,   2,   3,   4,   5,   6,   7,   8]])

In [ ]:
z.strides

(72, 8)

Visualizando os dados como bytes


In [ ]:
z.dtype = np.dtype('uint8')
z

array([[100,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,   0,
          0,   0,   0,   2,   0,   0,   0,   0,   0,   0,   0,   3,   0,
          0,   0,   0,   0,   0,   0,   4,   0,   0,   0,   0,   0,   0,
          0,   5,   0,   0,   0,   0,   0,   0,   0,   6,   0,   0,   0,
          0,   0,   0,   0,   7,   0,   0,   0,   0,   0,   0,   0,   8,
          0,   0,   0,   0,   0,   0,   0]], dtype=uint8)

In [ ]:
z.shape
z.strides

(72, 1)

## **Operações numericas: vetores**

In [ ]:
a = [1, 3, 5]
b = [3*x for x in a]
b


[3, 9, 15]

In [ ]:
a = np.array([1, 3, 5])
b = 3 * a
b

array([ 3,  9, 15])

In [ ]:
b-a

array([ 2,  6, 10])

In [ ]:
m = np.arange(6).reshape((2,3))
m

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b+m

array([[ 3, 10, 17],
       [ 6, 13, 20]])

## **Exemplos de vetorização e transmissão** 
## Funções

In [ ]:
def f(x):
  return x**2 - 3*x + 4

x = np.arange(1e5)
y = [f(i) for i in x]

y = f(x)
y

array([4.00000000e+00, 2.00000000e+00, 2.00000000e+00, ...,
       9.99910002e+09, 9.99930001e+09, 9.99950001e+09])